### ISSUE TITLE
Extension

### ISSUE THREAD

**Issue by RitaRamo** [jcarias/pa2015-classdiagram#1]
Já consegui extender sem problemas, já não me dá erro :) Já está feita a extensão, obrigada

**Comment by jcarias** [comment]
Em relação às duas primeiras questões se usares o outro projecto do repositório podes ver nesse projecto como é que se acede às cenas. Tem mais a ver com imports do que com as definições das classes. Em todo caso é um coisa que posso analisar depois.

Em relação ao tipo de retorno, o que tens de assumir é que os parâmetros virão preenchidos para o teu lado (o que efectivamente não acontece porque só quando cada uma das unidades vai ser exibida é que vai executar os métodos que implementarás no filtro e, só nessa altura, é que os parâmetros passarão a ter valores) em função do retorno é que um determinado elemento é ou não exibido.

PS: vou também enviar um email para garantir que recebes a resposta.

Depois falamos na segunda ou assim e eu ajudo-te com isso.

**Comment by jcarias** [comment]
Resolvido! Os Filtros agora já contemplam os elementos ligados aos elementos base.
Para além disso, os filtros voltaram a estar activos por omissão.

**Comment by RitaRamo** [comment]
Deixa, jão agora vou mostrar como tenho, estou ainda em directa de SIAD,
quando acabar SIAD, vou dormir. Mostro ao stor a implementação que fiz da
tua extensão anterior.

No dia 21 de dezembro de 2015 às 11:58, João Carias <
notifications@github.com> escreveu:

**Comment by jcarias** [comment]
Mas olha que basta actualizar o projecto para teres as correcções do teu lado.
